# Generated by Django 4.2.7 on 2025-10-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_ID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('Aadhar_Number', models.CharField(max_length=12)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('KYC_status', models.CharField(choices=[('Not_Updated', 'Not Updated'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Review', 'Review')], default='Not_Updated', max_length=20)),
                ('Aadhar', models.FileField(blank=True, null=True, upload_to='Aadhar/')),
                ('Profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Processing', 'Processing')], default='Pending', max_length=20)),
            ],
        ),
    ]
