# Generated by Django 4.2.7 on 2025-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userprofile_login_id_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Account_Balance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
